### ISSUE TITLE
Anti block break?

### ISSUE THREAD

**Issue by Wouter0100** [Hell-Fire/ControllerBlock#3]
Hey,

I have in my server controllerblock but lots of people use it for Duplicating (factory's) can you make if the controllerblock activited by redstone then check if the blocks break? (Torches fall)

Sorry for my very bad english..

Wouter0100

**Comment by Hell-Fire** [comment]
This is a known issue, just hadn't gotten around to adding it yet :)

Those blocks that are duplicating, I'd suggest adding those types to the [disallowed] list in the ControllerBlock.ini for now.
